#!/bin/bash
#
# Set the proxy for apt-get, aptitude, etc. Put this file in
# /etc/apt/apt.conf.d/
#
# author: Bean Zhang
# email: sjtuzb@gmail.com
#

Acquire::http::proxy "http://proxy.example.com:port/";
Acquire::https::proxy "https://proxy.example.com:port/";
Acquire::ftp::proxy "ftp://proxy.example.com:port/";

